# Copyright (c) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Check Results

on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: cache-pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-test-pip

    - name: install-pip
      run: |
        pip3 install wheel setuptools GitPython
        pip3 install junit2html

    - id: file_changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        output: 'json'

    - name: Check results
      id: results
      run: |
        latest=$(scripts/version_mgr.py -L)
        echo "version=${latest}" >> $GITHUB_OUTPUT;
        echo "Latest is ${latest}";

        # check if we have the board already, just in case, WIP
        for file in `cat $HOME/files_added.json | jq -r  '.[] '`; do
          if [[ ${file} == results/*sanitycheck* ]]; then
            echo "File ${file} not allowed."
            exit 1
          fi
          if [[ ${file} == results/* ]]; then
            echo "Verifying content of ${file}"
            fd=$(dirname $file)
            v=$(basename $fd)
            max_size=10
            cmd="python3 scripts/results_verification.py -Z ${v} -P ./${file} -S ${max_size}"
            echo $cmd
            eval $cmd
            if [ $? -eq 0 ]
            then
              echo "Results file succesfully verified"
            else
              echo "Results file verification failed"
              exit 1
            fi
          fi
        done

